//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erecruitment.WebApi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandJobExp_Benefit
    {
        public long ID { get; set; }
        public string Descr { get; set; }
        public Nullable<long> JobExperienceID { get; set; }
    
        public virtual Cand_JobExp Cand_JobExp { get; set; }
    }
}
