//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erecruitment.WebApi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cand_Course
    {
        public long ID { get; set; }
        public string Field { get; set; }
        public string Institution { get; set; }
        public string Location { get; set; }
        public string Duration { get; set; }
        public Nullable<int> IssueYear { get; set; }
        public string Endorsement { get; set; }
        public Nullable<long> CandidateID { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
