//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erecruitment.WebApi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cand_JobExp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cand_JobExp()
        {
            this.CandJobExp_Benefit = new HashSet<CandJobExp_Benefit>();
            this.CandJobExp_Responsibility = new HashSet<CandJobExp_Responsibility>();
        }
    
        public long ID { get; set; }
        public string Company { get; set; }
        public string Location { get; set; }
        public string Industry { get; set; }
        public string JobTitle { get; set; }
        public string JobFunction { get; set; }
        public string JobPositionLevel { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<int> Salary { get; set; }
        public string DirectBoss { get; set; }
        public string LeaveReason { get; set; }
        public Nullable<long> CandidateID { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandJobExp_Benefit> CandJobExp_Benefit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandJobExp_Responsibility> CandJobExp_Responsibility { get; set; }
    }
}
