//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erecruitment.WebApi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_WILAYAH_INDONESIA
    {
        public int ID { get; set; }
        public Nullable<int> ID_DARI_SOURCE { get; set; }
        public string KODE { get; set; }
        public string NAMA_WILAYAH { get; set; }
        public string KODE_PARENT { get; set; }
    }
}
