//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erecruitment.WebApi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Position
    {
        public long ID { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> DtmCreate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> DtmUpdate { get; set; }
        public string Position { get; set; }
        public string Lvl { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<long> JobTitleID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Job_Title Job_Title { get; set; }
    }
}
