//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erecruitment.WebApi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApp_Phase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobApp_Phase()
        {
            this.JobApp_Task = new HashSet<JobApp_Task>();
        }
    
        public long ID { get; set; }
        public string Phase { get; set; }
        public string Result { get; set; }
        public string Descr { get; set; }
        public Nullable<long> AppID { get; set; }
    
        public virtual Job_App Job_App { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApp_Task> JobApp_Task { get; set; }
    }
}
