//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erecruitment.WebApi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_KODEPOS
    {
        public int ID { get; set; }
        public Nullable<int> ID_DARI_SOURCE { get; set; }
        public string KELURAHAN { get; set; }
        public string KECAMATAN { get; set; }
        public string KABUPATEN { get; set; }
        public string PROVINSI { get; set; }
        public string KODEPOS { get; set; }
    }
}
