//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erecruitment.WebApi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_User
    {
        public long ID { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
        public Nullable<System.DateTime> DtmCreate { get; set; }
        public Nullable<System.DateTime> DtmUpdate { get; set; }
        public Nullable<long> CandidateID { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
